#!/usr/bin/env python3
"""
Bootstrap a full attempts ledger from history/*.txt.

Creates:
- ledger/attempts_full.jsonl  (1 JSON object per line; final newline ensured)
- scripts/attempts/*.md       (placeholder stubs, safe filenames)

Doctest:
>>> infer_riddle_id("58bZfQ1 blah")
'R1'
>>> infer_riddle_id("zrUfKaKV blah")
'R2'
>>> infer_riddle_id("nothing")
'GEN'
>>> safe_component("a b/c:d", 20)
'a_b_c_d'
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List

log = logging.getLogger("attempts_full_bootstrap")

def infer_riddle_id(text: str) -> str:
    t = text.lower()
    if "58bzfq1" in t:
        return "R1"
    if "zrufkakv" in t:
        return "R2"
    return "GEN"

def safe_component(s: str, maxlen: int = 120) -> str:
    assert maxlen >= 8
    s2 = re.sub(r"[^A-Za-z0-9._-]+", "_", s).strip("_")
    if not s2:
        s2 = "unknown"
    return s2[:maxlen]

def sha256_hex(path: Path) -> str:
    assert path.is_file(), f"not a file: {path}"
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--history", default="history")
    ap.add_argument("--out", default="ledger/attempts_full.jsonl")
    ap.add_argument("--stubs", default="scripts/attempts")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    logging.basicConfig(level=(logging.DEBUG if args.verbose else logging.INFO),
                        format="%(levelname)s:%(name)s:%(message)s")

    hist = Path(args.history)
    outp = Path(args.out)
    stub_dir = Path(args.stubs)

    assert hist.is_dir(), f"missing history dir: {hist}"
    outp.parent.mkdir(parents=True, exist_ok=True)
    stub_dir.mkdir(parents=True, exist_ok=True)

    files = sorted([p for p in hist.iterdir() if p.is_file() and p.suffix.lower() == ".txt"])
    assert files, "history/*.txt empty; nothing to bootstrap"

    rows: List[Dict[str, Any]] = []
    for i, p in enumerate(files, 1):
        rel = f"history/{p.name}"
        inp_sha = sha256_hex(p)

        # attempt id stable by index (deterministic because files sorted by name)
        attempt_id = f"H9{i:05d}"

        layer_id = p.stem  # e.g. H00061__anchors_ctx
        stub_name = safe_component(f"{attempt_id}__{layer_id}__PLACEHOLDER.md", 180)
        stub_path = stub_dir / stub_name

        # lightweight sniff for riddle id (optional)
        head = p.read_text(encoding="utf-8", errors="replace")[:4000]
        rid = infer_riddle_id(head)

        row = {
            "attempt_id": attempt_id,
            "layer_id": layer_id,
            "status": "PLACEHOLDER",
            "claim": "UNVERIFIED",
            "intent": f"Placeholder for {rel} (riddle={rid}); upgrade with real layer mapping + scripts.",
            "source_artifact": rel,
            "transform_tool": f"scripts/attempts/{stub_name}",
            "command_line": "",
            "input_sha256": inp_sha,
            "output_sha256": "",
            "output_paths": [],
            "expected_output": "",
            "what_failed": "",
            "notes": "autogenerated placeholder row",
            "next_tests": "triage history file; link concrete OUT artifacts; promote to PASS/FAIL with reproducible script",
        }
        rows.append(row)

        if args.force or not stub_path.exists():
            stub_path.write_text(
                "\n".join([
                    f"# {attempt_id} — PLACEHOLDER",
                    "",
                    f"- source: `{rel}`",
                    f"- input_sha256: `{inp_sha}`",
                    f"- inferred_riddle: `{rid}`",
                    "",
                    "## What this attempt was doing",
                    "(fill in)",
                    "",
                    "## Repro commands",
                    "```bash",
                    "# (fill in reproducible commands)",
                    "```",
                    "",
                    "## Outputs",
                    "- (fill in output paths + sha256)",
                    "",
                    "## Result",
                    "- status: PLACEHOLDER",
                    "- claim: UNVERIFIED",
                    "",
                    "## Next tests",
                    "(fill in)",
                    "",
                ]) + "\n",
                encoding="utf-8",
                newline="\n",
            )

    # Write JSONL: one JSON object per line + final newline
    out_lines = [json.dumps(r, ensure_ascii=False, sort_keys=True) for r in rows]
    outp.write_text("\n".join(out_lines) + "\n", encoding="utf-8", newline="\n")

    log.info("wrote %s rows=%d", outp, len(rows))
    log.info("stubs_dir=%s", stub_dir)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
